name: 'Apk Info Action'
description: 'This GitHub Actions gets information of Android apk file.'
author: 'Hiroyuki Kusu'
branding:
  icon: 'info'
  color: 'white'
inputs:
  apk-path:
    description: ''
    required: true
outputs:
  version-code:
    description: ''
  version-name:
    description: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
